export default {
  headNavArr: [],
  slideIndex: 0,
  category: "",
  kind: {
    NavigateTitle: [],
    NavigateData: [],
    NavigateId: [],
    NavigateDescribe: [],
    headerTitle: [],
  },
  kindInfo: [],
  flag: false,
  TopImage: [],
  FullToastImage: [],
  searchText: [],
  transition: false,
  LodUnReadNotice: false,
  topImg: [true],
  flagRight: false,
  moticeFlag: true,
  SHOWMk: [],
  index: null,
  userId: false,
  userLlogin: true,
  initialSlide: null,
  loginflag: true,
  Discount: false,
  footerIndex: 1,
  HeaderShow: true,
  home: {
    moreProduct: [],
    moreProductImg: [],
    homeToast: [],
    BUOY: [],
    flag: true,
    index: 2,
    getMoreflag: true,
    getMoreHotflag: true,
    NewIndex: 2,
    swiperSlides: [],
    HotIndex: 2,
    loadingFlag: 0,
    moreHotProduct: [],
    specialArr: [],
    specialTimeLimitArr: [],//限时特惠
    moreHotProductImg: [],
    HomeAritcal: [],
    specialAreaContent: [],
    originalCompilation: [],
    HotSaleProduct: [],
    NewProduct: [],
    RecommendProduct: [],
    Product: [],
    scrollTop: 0,
    adversitingone: [
      {
        Url: "",
        ImageUrl: ""
      }
    ],
    adversitingtwo: [
      {
        Url: "",
        ImageUrl: ""
      }
    ],
    adversitingthree: [
      {
        Url: "",
        ImageUrl: ""
      }
    ]
  },
  ms: {
    flag: true,
    MsAritcal: [],
    moreProduct: [],
    HotSaleProduct: [],
    moreProductImg: [],
    index: 2,
    moreHotProductImg: [],
    swiperSlides: [],
    getMoreflag: true,
    getMoreHotflag: true,
    NewIndex: 2,
    HotIndex: 2,
    moreHotProduct: [],
    categoryArr: [],
    categoryArrBefore: [],
    NewProduct: [],
    loadingFlag: 0,
    scrollTop: 0,
    categoryAreaArr: [],
    hotRecommendVertical: [],
    catetoryAfter: [],
    hotRecommendLevel: [],
    categorys: [],
    categroysKind: [],
    Describe: [],
    categroyList: [],
    cateTitle: ""
  },
  jjjz: {
    flag: true,
    index: 2,
    moreProduct: [],
    moreProductImg: [],
    moreHotProduct: [],
    moreHotProductImg: [],
    swiperSlides: [],
    getMoreflag: true,
    getMoreHotflag: true,
    HotSaleProduct: [],
    NewIndex: 2,
    HotIndex: 2,
    categoryArr: [],
    jjjzAritcal: [],
    NewProduct: [],
    categoryAreaArr: [],
    categoryArrBefore: [],
    hotRecommendVertical: [],
    scrollTop: 0,
    loadingFlag: 0,
    hotRecommendLevel: [],
    categorys: [],
    catetoryAfter: [],
    categroysKind: [],
    Describe: [],
    categroyList: [],
    cateTitle: ""
  },
  jydq: {
    flag: true,
    index: 2,
    swiperSlides: [],
    categoryArr: [],
    jydqAritcal: [],
    moreProduct: [],
    moreHotProduct: [],
    moreProductImg: [],
    moreHotProductImg: [],
    categoryArrBefore: [],
    getMoreflag: true,
    getMoreHotflag: true,
    HotSaleProduct: [],
    NewIndex: 2,
    HotIndex: 2,
    NewProduct: [],
    categoryAreaArr: [],
    hotRecommendVertical: [],
    scrollTop: 0,
    hotRecommendLevel: [],
    loadingFlag: 0,
    categorys: [],
    catetoryAfter: [],
    categroysKind: [],
    Describe: [],
    categroyList: [],
    cateTitle: ""
  },
  myyp: {
    flag: true,
    index: 2,
    swiperSlides: [],
    moreProduct: [],
    moreProductImg: [],
    moreHotProductImg: [],
    myypAritcal: [],
    getMoreflag: true,
    getMoreHotflag: true,
    NewIndex: 2,
    HotIndex: 2,
    categoryArr: [],
    moreHotProduct: [],
    categoryArrBefore: [],
    categoryAreaArr: [],
    HotSaleProduct: [],
    NewProduct: [],
    loadingFlag: 0,
    hotRecommendVertical: [],
    scrollTop: 0,
    hotRecommendLevel: [],
    categorys: [],
    categroysKind: [],
    Describe: [],
    categroyList: [],
    cateTitle: "",
    catetoryAfter: []
  },
  mzgh: {
    mzghAritcal: [],
    flag: true,
    index: 2,
    swiperSlides: [],
    categoryArr: [],
    moreProduct: [],
    moreProductImg: [],
    moreHotProductImg: [],
    categoryArrBefore: [],
    NewProduct: [],
    categoryAreaArr: [],
    moreHotProduct: [],
    scrollTop: 0,
    HotSaleProduct: [],
    hotRecommendVertical: [],
    loadingFlag: 0,
    hotRecommendLevel: [],
    categorys: [],
    getMoreflag: true,
    getMoreHotflag: true,
    NewIndex: 2,
    HotIndex: 2,
    categroysKind: [],
    catetoryAfter: [],
    Describe: [],
    categroyList: [],
    cateTitle: ""
  },
  qcbk: {
    flag: true,
    index: 2,
    swiperSlides: [],
    moreProduct: [],
    moreProductImg: [],
    moreHotProductImg: [],
    qcbkAritcal: [],
    getMoreflag: true,
    getMoreHotflag: true,
    NewIndex: 2,
    HotIndex: 2,
    moreHotProduct: [],
    categoryArr: [],
    categoryArrBefore: [],
    categoryAreaArr: [],
    HotSaleProduct: [],
    scrollTop: 0,
    loadingFlag: 0,
    hotRecommendVertical: [],
    hotRecommendLevel: [],
    categorys: [],
    catetoryAfter: [],
    categroysKind: [],
    Describe: [],
    categroyList: [],
    cateTitle: ""
  },
  whjy: {
    flag: true,
    index: 2,
    swiperSlides: [],
    moreProduct: [],
    moreProductImg: [],
    moreHotProductImg: [],
    whjyAritcal: [],
    getMoreflag: true,
    getMoreHotflag: true,
    NewIndex: 2,
    HotIndex: 2,
    moreHotProduct: [],
    categoryArr: [],
    categoryArrBefore: [],
    categoryAreaArr: [],
    HotSaleProduct: [],
    scrollTop: 0,
    loadingFlag: 0,
    hotRecommendVertical: [],
    hotRecommendLevel: [],
    categorys: [],
    catetoryAfter: [],
    categroysKind: [],
    Describe: [],
    categroyList: [],
    cateTitle: ""
  },
  zqhd: {
    scrollTop: 0,
    loadingFlag: 0,
    advertConfig: [],
    banner:[],
    skillData:[],
    tuangouData:[],
    fullDelivery: {
      productList: [],
      Code: '',
      Image: '',
      Title: '',
    },
    descendingData: {
      productList: [],
      Code: '',
      Image: '',
      Title: '',
    },
    GiftData: {
      productList: [],
      Code: '',
      Image: '',
      Title: '',
    },
    information1:[],
    information2:[],
    homeVideo:[],
  },
}